### ISSUE TITLE
Pay for a server capable of running Mattermost

### ISSUE THREAD

**Issue by terracoin** [terracoin/proposals#10]
This is a proposal to get a server capable of running Mattermost for a year.

I am asking for 3448 TRC x $.35 USD (current price), which is approximately $1200 USD.

The Terracoin Foundation wants to set up a Mattermost server to bridge between Telegram, Slack, and Discord.  This will help unify the community, create long term message storage and will help with getting all questions answered in a timely fashion.  We will also be moving over the other TRC Foundation hosted sites such as the explorer, wiki, stats and masternode pages so that they are more reliable.  We will keep the web hosting on Godaddy for now.

The server we are looking at has 16GB RAM, 4 Cores and a 230 GB SSD.

Thanks!

P.s. I put in a similar proposal a day before the superblock just to see if someone could shove a proposal through right before the superblock.  Sentinel is smart enough not to let that happen so the proposal did not go through even though it got enough votes.  You can check the explorer and the last superblock and see it wasn't paid out.  https://explorer.terracoin.io/block/97d016f52e65c259b5bcffc30ee8d730bfc5bd78fe00307aa51a375a4c8fc0a8

**Comment by terracoin** [comment]
This needs to be re-submitted

**Comment by terracoin** [comment]
Please vote yes for this proposal!
gobject vote-many 6694a632f0a1efc2bdef793ba146f0a9b566ddc27a65a93f16988b6d1a608606 funding yes

**Comment by walkjivefly** [comment]
Excellent idea! I hate Discord and hate having to use so many different platforms to keep up with different coins and projects. Voted yes.

**Comment by clockuniverse** [comment]
Proposal passed!  Mattermost invite: https://mattermost.terracoin.io/signup_user_complete/?id=ohowtejzq3br7kp66qe466b8my

I probably should have updated this a long time ago.
