### ISSUE TITLE
Terracoin masternode Guide

### ISSUE THREAD

**Issue by u3mur4** [terracoin/proposals#3]
I created a masternode setup guide ([https://github.com/u3mur4/terracoin](https://github.com/u3mur4/terracoin)) with automatic vps setup script. I also posted two youtube videos where I show the exact setup steps. I published the guide in advance to help the community. Anyone who used my guide or find the guide helpful please vote yes.

```bash
gobject vote-many f59edb2d130f39756d279cc04d2c15fd56d9a4c52076523fcfe987df1556038a funding yes
```

Requested TRC: 500

**Comment by lsb108** [comment]
I do not know Vote for you yet! When I made Votem it was reported Error.

**Comment by clockuniverse** [comment]
I voted yes on his proposal because he put a lot of work into it (he made videos!) and because he worked on a hope and a dream!  I recommend everyone vote yes on this as well!

gobject vote-many f59edb2d130f39756d279cc04d2c15fd56d9a4c52076523fcfe987df1556038a funding yes

**Comment by lsb108** [comment]
He is so cute and humble! I evaluated and asked to pay a reward for his work of 1000 TRC ... That can let the community know that: We love the talent, we need the talented people ... They will receive be worthy reward!

**Comment by terracoin** [comment]
Done.

**Comment by txpvcoach** [comment]
I received this error trying to create a second masternode on Vultr in a new VPS
Please help.
2018-06-11 17:10:33 (108 MB/s) - ‘trc.py’ saved [10349/10349]

Traceback (most recent call last):
  File "trc.py", line 31, in <module>
    SERVER_IP = urlopen('https://api.ipify.org/').read()
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1241, in https_open
    context=self._context)
  File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno -3] Temporary failure in name resolution>
root@GRTRC02MN:~#
