### ISSUE TITLE
Thank you clockuniverse

### ISSUE THREAD

**Issue by JacobKerr** [terracoin/proposals#4]
If you are reading this you have probably also been helped by clockuniverse.

He is the President of the Terracoin Foundation and is the reason master nodes exist on Terracoin and why you have the opportunity to vote on this. While he likes to say "he works on the coin" he is the head developer and for a long time now been spending his own money to get changes made to the wallet, blockchain, website and most recently he had to dump 4BTC into Nethash to get the blockchain moving after our hard fork. 

While I know 10K TRC is nowhere near the amount of money you have put in I would like to at least give the community the opportunity to make this gesture of thanks for what you have done to get us this far. 
I look forward to your leadership and steady hand as you help guide this coin into the unknown.

**Comment by JacobKerr** [comment]
To vote yes use this command:
gobject vote-many b565760d468a21bcc3d247dc75d1beecb4fbec12443a8b54a62a480581ee0399 funding yes

To vote no use this command:
gobject vote-many b565760d468a21bcc3d247dc75d1beecb4fbec12443a8b54a62a480581ee0399 funding no

to abstain use this command: (we think)
gobject vote-many b565760d468a21bcc3d247dc75d1beecb4fbec12443a8b54a62a480581ee0399 funding abstain

**Comment by ghost** [comment]
I agree and I'm voting yes, but why shouldn't we just make him recover all the money he invested and all the time he dedicated to the project?

**Comment by JacobKerr** [comment]
There are only so many coins created each month for one thing and I was unsure how the community would feel about this request.

**Comment by terracoin** [comment]
Done.
