### ISSUE TITLE
Masternode Tutorial Reward

### ISSUE THREAD

**Issue by lamalamic** [terracoin/proposals#5]
### First of all, hello everyone!
I was asked by Clock Universe to put in a proposal for reward for my comprehensive masternode tutorial for Windows users. You can download the tutorial here:

### [Step by step Masternode tutorial for Windows users](https://github.com/terracoin/proposals/files/1376191/Step.by.step.Masternode.tutorial.for.Windows.users.pdf)

In the moment of writing of the tutorial there were not many guides available so I basically had to use a trial and error method and give it up my own time. The guide was spread way ahead of the hardfork so everyone, no matter the computer knowledge, was able to set up the masternode. I love the community which has formed around the coin and I love to be part of it. That is the main reason I decided to write the tutorial. You can usually find me on the telegram channel where I do my best to help others.

In case you have found my tutorial, advice and community work helpful, please, run my proposal through the debug console. I wasn't sure about the reward amount so I got inspired by similar proposal regarding masternode guide. There are almost 500 masternodes running in the moment. Therefore, I think it is fair to ask for 500 TRC, which is 1 TRC per each masternode. This will not cost you anything, because the reward is paid by decentralized governance fund. Additionally, you will give me motivation boost to help the community even more.

The command to put into the debug console to vote for my proposal:
`gobject vote-many e0e01f414016b77b1b58b6d43da8a21c4809fcaf5aa2b520bfb0326412f618e9 funding yes`

### Thank you everyone, have a great day and let's build the nicest community we possibly can!

<br/>
<br/>

![Terracoin](http://www.terracoin.io/img/terracoin-logo.svg)

**Comment by terracoin** [comment]
Done

**Comment by lamalamic** [comment]
Thank you everyone!
