### ISSUE TITLE
Advertising and sponsorship Proposal

### ISSUE THREAD

**Issue by Eyeswide5hut** [terracoin/proposals#7]
I, myself, Eyes Wide Shut would like to put forwards a proposal for your consideration.

This proposal is based on graphic design and marketing.
I have a history of working in graphic design and even had my own studio called Two Chips And an Egg Design.
I quit the industry because I wasn't keen on the corporate side of the work and felt a little bit like I was selling my soul, but I still do odd jobs freelance when I feel like it as I have a real passion for design. Since joining the Terracoin community I have felt inspired to start again. This, combined with another of my passions, charitable work has really motivated me to make this pitch to you today.

I would like to ask for 5,160 TRC and in return I will create a comprehensive package to kick start a PR campaign which will aim at gaining some real momentum and enthusiasm for Terracoin. This should in turn raise the value of the TRC coin and plant seeds to grow our community.

This package will consist of a sports sponsorship, a brand design package and some ready-to-use adverts and PR material for use on websites or advertising campaigns.

The sports sponsorship is for an asylum seeker and refugee football team, this team is already functioning and have taken part in competitions like the FA Peoples' Cup. They also get invited to regional tournaments and play friendlies in schools and colleges. Now the team want to separate from their church-based charity and make themselves into an independent refugee and asylum seeker based football team. They train on a weekly basis and post social media updates along with pictures when they have a game, sometimes garnering media attention due to the fact they are a team of refugees, previously they featured in a national newspaper.

For this sponsorship the team would require the purchase of:
a matching football kit   x 13        
 -costing 2800 TRC or £390

the new club emblem printing onto the kit                                                                                                  
 -costing 290 TRC  or £40

Sponsor logo printing in large format on the front of the kit                                                                    -
 -costing 350 TRC or £50

Two kit bags to transport the kit too and from games                                                                               
 -costing 150 TRC or £20

Training bibs for practice sessions                                                                                                                 
 -costing  400 TRC or £56

and 4x match regulation footballs                                                                                                                 
 -costing 170 TRC or £25

Which comes to a grand total of:  4160 TRC or £582 (these figures where rounded up and down to keep the numbers simple any extra needed will be funded by myself)

This opportunity arose after a family member, who is also the coach for the team asked me to re-design the team emblem which I have already completed. There will be a PR push once the team have their new kit and we will aim to have pictures and articles printed in different media outlets including their own social media. Not only this, but it will also look very good on the Terracoin website, possibly under community or the terracoin foundation and and is a great start to adding more real world content for the brand and an interesting talking point for newcomers. I really don't think opportunities come around like this very often and its one I think we should embrace as a community.

Now for the second part of this application i am requesting 1000 TRC for my services as a graphic designer. i have already completed some aspects of this proposal but would like to spend some more time working on building a campaign around Terracoin and start marketing it more.
i have spent longer than i will admit putting together this collection of work and will complete a total of:
5 x Facebook ready adverts
5 x Twitter ready adverts
2 x banners
1 x skyscraper
1 x sticker design
1 x Poster
1 x business card template
and the brand design packet including different logo layouts and colour schemes.

As a bonus I will also design a set of TERRACOIN emoji's that will be uploaded to discord and other social media.

Some of these have already been completed so are shared in a Dropbox folder seen here: https://www.dropbox.com/sh/d6ed0onlo3au50a/AADMZTMnyx-x8LfKvzf1e8Uya?dl=0
Others I will continue to work on and release to the community when completed.

Thank you for your time, 
I'm here to help and answer/rid any questions/worries you may have, I'm most active on discord and it would be nice to get to know some members a bit better so don't hesitate to drop in for a chat!
Thanks again,
Eyes Wide Shut. 

Ok well clockuniverse has pointed out I have missed some pretty crucial details!
I forgot to mention the team is called Halifax United and are based in a town called Halifax in the north of England. Due to the fact they are currently linked to a church, they don't have a website at the moment but it is something I will be working on with them to set up in the coming days/weeks. So there is another chance to get the word out about Terracoin.
If you are interested, I have some pictures of the team from previous games they have played.

The team are also not currently in a league so only play friendlies and in cups so this sponsorship fee is to cover supplies needed by the team and they will continue to advertise Terracoin for a minimum duration of 1 year from the arrival of the equipment.

Of course, I will work on a design and write up for the website but I think it would be best to wait until we have the kits and can incorporate pictures of the team in the kit.
I also really like the idea of getting some extra shirts printed for the community so if this proposal passes I will coordinate an extra purchase of shirts for all interested!

Thanks for the positive feedback! 
Eyes Wide Shut

OK fingers crossed it all submitted now! Thanks for the walk through, made it really simple!
Here is the voting hash for you:

gobject vote-many 16af2bc8c4e719d8bb9d53ef8e5a12e6747e5d33fd15e556b09985b2c8884942 funding yes

**Comment by JacobKerr** [comment]
I would vote for this!
can you also look into getting team jerseys as I would love to have one with our logo on it.

**Comment by lamalamic** [comment]
Do you think you could also include a graphical proposal as how you imagine this donation could be featured on the terracoin website? Otherwise, I am definitely in!

**Comment by Eyeswide5hut** [comment]
ok proposal is live! here is the voting hash: 
gobject vote-many 16af2bc8c4e719d8bb9d53ef8e5a12e6747e5d33fd15e556b09985b2c8884942 funding yes

and thank you for taking time to read my proposal i look forward to hearing back from some of you!
i will add a couple more bits to the Dropbox tomorrow before i start work.
thanks

**Comment by Eyeswide5hut** [comment]
WOW! 53 positive votes already! I am so happy people are getting behind my idea and placing their trust in me, i'm honored! more work going into the Dropbox now

**Comment by lsb108** [comment]
You will get my 'yes'! As Jakob has said: we hope to have the TerraCoin logo on the player's shirt!

**Comment by Eyeswide5hut** [comment]
Ok well this looks like it's going to pass now so I am starting to think about buying extra shirts for all those interested. Unfortunately it seems quite hard to get the attention of everyone in one place. So I will start here, please comment or message either here, Twitter or discord if you are genuinely interested in purchasing an extra jersey I will start a list. And then when it is closer to the time of order I will contact you for further details. 
Thanks again for the support and I hope this can be the start of somthing great and a fruitful relationship!
